### PR TITLE
Added Maps extension role

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Tested manually

### CODE REVIEW

**Comment by bd808** [comment]
@JeroenDeDauw please submit this as a Gerrit patch (https://gerrit.wikimedia.org/r/#/admin/projects/mediawiki/vagrant). Thanks.

**Comment by JeroenDeDauw** [comment]
Can you please indicate this is not the main repo in the description and/or the PR template so people don't waste their time like this?

**Comment by bd808** [comment]
I added "This is a mirror from https://gerrit.wikimedia.org." to the main description.

**Comment by JeroenDeDauw** [comment]
Thank you

**Pull request closed without merging**
